### ISSUE TITLE
`Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance->mockMethodArguments()` fails to mock various Reflection classes provided by php's standard library

### ISSUE THREAD

**Issue by sevidmusic** [sevidmusic/PHPMockingUtilities#36]
`Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance->mockMethodArguments()` fails to mock various Reflection classes provided by php's standard library

For example, the following integration test fails for the indicated Reflection classes:

```
<?php

require(
    str_replace(
        'tests' . DIRECTORY_SEPARATOR . 'integration',
        'vendor',
        __DIR__,
    ) . DIRECTORY_SEPARATOR . 'autoload.php'
);

use \Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance;
use \Darling\PHPReflectionUtilities\classes\utilities\Reflection as DarlingReflection;
use \Darling\PHPTextTypes\classes\strings\ClassString;
use \Darling\PHPTextTypes\classes\strings\Text;

enum FooBarBaz
{
    case Foo;
    case Bar;
    case Baz;
}

enum FooBarBazBacked: string
{
    case Foo = 'foo';
    case Bar = 'bar';
    case Baz = 'baz';
}

function bazzerBazFoo(): void {}

function intGenerator(int $max): Generator {
    for ($i = 1; $i <= $max; $i++) {
        yield $i;
    }
}

/**
 * Return an instance of either a ReflectionClass or
 * a ReflectionProperty.
 *
 * @return ReflectionClass<object>|ReflectionProperty
 *
 */
function instanceOfAStandardLibraryReflectionType(): mixed
{
    /** @var array<ReflectionClass<object>|ReflectionProperty> $classes */
    $classes = [
        new DarlingReflection(new ClassString(Text::class)),
        new Reflection(),
        new ReflectionClass(Text::class),
        new ReflectionClass(Text::class),
        new ReflectionException(),
        new ReflectionFiber( new Fiber(function(): string { return 'foo'; })),
        new ReflectionIntersectionType(),
        new ReflectionNamedType(),
        new ReflectionObject(new Text('foo bar baz')),
        new ReflectionProperty(Text::class, 'string'),
        new ReflectionUnionType(),
        ReflectionReference::fromArrayElement(['foo'], 0), # Fails
        new ReflectionClassConstant(MockClassInstance::class, 'CONSTRUCT'), # Fails
        new ReflectionEnum(FooBarBaz::class), # Fails
        new ReflectionEnumBackedCase(FooBarBazBacked::class, 'Bar'), # Fails
        new ReflectionEnumUnitCase(FooBarBaz::class, 'Foo'), # Fails
        new ReflectionExtension('curl'), # Fails
        new ReflectionFunction('bazzerBazFoo'), # Fails
        new ReflectionGenerator(intGenerator(PHP_INT_MAX)), # Fails
        new ReflectionMethod(Text::class, '__toString'), # Fails
        new ReflectionParameter([Text::class, '__construct'], 0), # Fails
        # NOT TESTED YET: new ReflectionZendExtension(''),
        # NOT TESTED YET: new ReflectionAttribute(),
   ];
    return $classes[array_rand($classes)];
}


$mi = new MockClassInstance(
    new DarlingReflection(
        new ClassString(
            instanceOfAStandardLibraryReflectionType()
        )
    )
);

var_dump($mi->mockInstance());

```

The error seems to be a result of the the fact that method arguments that expect a string are mocked by an instance of a [MockString](https://github.com/sevidmusic/PHPMockingUtilities/blob/main/src/classes/mock/values/MockString.php).

From [\Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance](https://github.com/sevidmusic/PHPMockingUtilities/blob/main/src/classes/mock/values/MockClassInstance.php) 

```
    private function generateMockClassMethodArguments(
         string|object $class,
         string $method
    ): array
    {
        $classString = new ClassString($class);
        $reflection = new Reflection($classString);
        $defaults = array();
        if(method_exists($class, $method)) {
            foreach (
                $reflection->methodParameterTypes($method)
                as
                $name => $types
            ) {
                foreach($types as $type) {
                    // ...
                    if ($type === self::STRING) {
                        // Issue 36 seems to be the result of using a MockString to mock a string when a class-string is expected:
                        // @see https://github.com/sevidmusic/PHPMockingUtilities/issues/36
                        $defaults[$name] = $this->mockString();
                        continue;
                    }
                    // ...
                }
            }
        }
        return $defaults;
    }

```

**Comment by sevidmusic** [comment]
This issue is still a problem. While working on the [PHPJsonUtilities]() library, the following error kept occuring:

```
Warning: Uncaught ReflectionException: Class "MockStringMoM7pWJRxObOmpKdDSkRw6iHjtbI722gOd3hF4H" does not exist in /home/darling/Git/PHPJsonUtilities/vendor/darling/php-mocking-utilities/src/classes/mock/values/MockClassInstance.php:194
Stack trace:
#0 [internal function]: ReflectionClass->__construct()
#1 /home/darling/Git/PHPJsonUtilities/vendor/darling/php-mocking-utilities/src/classes/mock/values/MockClassInstance.php(194): ReflectionClass->newInstanceArgs()
#2 /home/darling/Git/PHPJsonUtilities/vendor/darling/php-mocking-utilities/src/classes/mock/values/MockClassInstance.php(149): Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance->getClassInstance()
#3 php shell code(1): Darling\PHPMockingUtilities\classes\mock\values\MockClassInstance->mockInstance()
#4 {main}
  thrown in /home/darling/Git/PHPJsonUtilities/vendor/darling/php-mocking-utilities/src/classes/mock/values/MockClassInstance.php on line 194

```

Further investigation is needed.
